### ISSUE TITLE
Remove Cluster Items?

### ISSUE THREAD

**Issue by ptsequeira** [hansemannn/titanium-google-maps#100]
There is a way to remove all Cluster Items, or remove a single one?

Thanks

**Comment by hansemannn** [comment]
There is a `removeClusterItem` and `clearClusterItems` method :-). Did you try those?

**Comment by hansemannn** [comment]
Added the docs in https://github.com/hansemannn/titanium-google-maps/commit/e221c9561b509fea50d27a26a9a0b00ba4a76655, thanks again!

**Comment by ptsequeira** [comment]
@hansemannn Sorry, I didn't see these methods in the docs and assumed that they didn't exist

Thanks

**Comment by hansemannn** [comment]
That's because I added them after you opened the issue 🙌.
