### ISSUE TITLE
No map during type "MAP_TYPE_SATELLITE"

### ISSUE THREAD

**Issue by oakleaf** [hansemannn/titanium-google-maps#104]
For some reason, I cant change the map type. The type "MAP_TYPE_SATELLITE" nor the other ones except the hybrid works for me.

Also, when I zoom in, the quality doesnt change, it's like zoom level 10 is the best zoom level, and when I zoom in further nothing happens with the vectors so it's a really poor resolution when I go in a couple of notches.

No error messages or anything, just no map showing.

**Comment by oakleaf** [comment]
(I use the Exact same code as the app.js example and only change maptype to: "MAP_TYPE_SATELLITE")

**Comment by hansemannn** [comment]
Works for me. Make sure to call it on the module namespace, so if you are using `var GMS = require('ti.googlemaps')`, the constant is accessed via `GMS.MAP_TYPE_SATELLITE`. Also ensure to set it on creation and via the `mapType` property.

**Comment by oakleaf** [comment]
Hello Hansemannn, Yes ofc Im trying to do that. Since I use your exact code from the readme file. The problem still exists even when I use your code directly. Maybe it has something to do with my ios version or something?

Here's more information about my setup, if it can be of any help:

Operating System
  Name                        = Mac OS X
  Version                     = 10.12.6

Node.js
  Node.js Version             = 4.6.0
  npm Version                 = 2.15.9

Appcelerator CLI
  Installer                   = 4.2.9
  Core Package                = 6.2.3

Titanium CLI
  CLI Version                 = 5.0.14
  node-appc Version           = 0.2.41

Titanium SDKs
  6.1.2.GA
    Version                   = 6.1.2
    node-appc Version         = 0.2.43
