### ISSUE TITLE
Map graphics not shown - map is suddenly completely blank

### ISSUE THREAD

**Issue by bitfabrikken** [hansemannn/titanium-google-maps#84]
Suddenly today while coding, the map is no longer shown. Well the map view itself is shown, there's just no data loaded on the map - no satellite etc.
Have tried changing between normal / satellite but no dice.

The errors I see both on device and in simulator are all similar to this:
`
ClientParametersRequest failed, 7 attempts remaining (0 vs 11). Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://clients4.google.com/glm/mmap, _kCFStreamErrorCodeKey=-2102, NSErrorFailingURLKey=https://clients4.google.com/glm/mmap, NSLocalizedDescription=The request timed out., _kCFStreamErrorDomainKey=4, NSUnderlyingError=0x791ca4c0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102}}}
`

Happens on iOS 10.3, 10.1, 9.3.5
And on Ti SDK 6.0.2.GA and 6.0.3.GA
And on ti.googlemaps 3.2.1 and 3.3.1

I verified I have the correct API key entered so it's not that either.

Any ideas?

**Comment by bitfabrikken** [comment]
Probably not the issue, but I first noticed this today after I upgraded Xcode from 8.1.x to 8.3.2

**Comment by yozef** [comment]
Scared me there for a while, seems it's on your end as the map tiles are loading as expected (with their polygons, annotations in my case).

Check your Google Console, maybe your request limit?

**Comment by bitfabrikken** [comment]
Annotations and polygons work fine. It's the tile graphics themselves which are blank.

Haven't hit any limit I don't think? I can't see any limits in the Google Developers Console - can you direct me to where that is perhaps?

**Comment by yozef** [comment]
https://console.developers.google.com/
It's the same place you got your API Key. Check that Project's API requests and if any errors appear there.

**Comment by bitfabrikken** [comment]
0 errors, 6,696 requests for the last 30 days, according to the console - and the quotas are set to unlimited. 
The live app on the App Store also has this problem (was fine earlier today too).

**Comment by bitfabrikken** [comment]
Just tried compiling the module with XCode 8.3.2 - that did not help either.

**Comment by yozef** [comment]
That's odd... your Prod version suddenly stopped loading the map tiles... 
Did you use an older ti.googlemaps when you packaged your app?

**Comment by bitfabrikken** [comment]
I'm beginning to think the Google server instance the app is connecting to
for tiles is down.

**Comment by bitfabrikken** [comment]
Oh, egg on my face. I think the IT crew here in my office space has closed off some outgoing ports today. Grr. Sorry for the bother @yozef :)

**Comment by yozef** [comment]
hehehe no worries.
