### ISSUE TITLE
customView for Annotation ?

### ISSUE THREAD

**Issue by DouglasHennrich** [hansemannn/titanium-google-maps#86]
There's no `customView` property for Annotation?

I only saw `infoWindow`

Thanks

**Comment by hansemannn** [comment]
Good idea! https://github.com/hansemannn/titanium-google-maps/pull/87

**Comment by DouglasHennrich** [comment]
Also, there's a way to know when the user click on `MyLocationBtn` ?

**Comment by hansemannn** [comment]
You tried `locationclick` on your map-view instance?
