### ISSUE TITLE
MapView.getAnnotations( ) ?

### ISSUE THREAD

**Issue by DouglasHennrich** [hansemannn/titanium-google-maps#91]
There's a way to get all annotations on the map ?

`.getAnnotations()` it's not working =/ I look through the module's class and I didn't find it exposed

Thanks

**Comment by hansemannn** [comment]
There is a property called `markers` which includes all the marker/annotation objects. It primarily used internally, but it should also be available from the public API. May be a good idea to call it `annotations` for parity,

**Comment by DouglasHennrich** [comment]
Yea thats right... `$.mapView.markers` returns all annotations. Could be great to change it's name and expose the `getAnnotations()` function =)
