### ISSUE TITLE
Allow rotation change in Annotation.updateLocation

### ISSUE THREAD

**Issue by mcongrove** [hansemannn/titanium-google-maps#92]
Would it be possible to allow annotation rotation to be changed from within the updateLocation method, rather than just lat/lon?

**Comment by hansemannn** [comment]
Added https://github.com/hansemannn/titanium-google-maps/pull/93, try it out!

**Comment by yozef** [comment]
You should find this feature in 3.6.0
https://github.com/hansemannn/titanium-google-maps/releases/tag/v3.6.0

**Comment by hansemannn** [comment]
Thanks @yozef for the review!

**Comment by mcongrove** [comment]
You may want to point out in the docs that this only works if `animated: true` is set. That confused me for a bit!

**Comment by hansemannn** [comment]
Whoops, forgot about that. https://github.com/hansemannn/titanium-google-maps/pull/94 will take care of that.

**Comment by hansemannn** [comment]
@mcongrove New release drafted ~ https://github.com/hansemannn/titanium-google-maps/releases/tag/v3.6.1-beta.1
