### ISSUE TITLE
Google Maps SDK for iOS requires GoogleMaps.bundle to be part of your target under 'Copy Bundle Resources'

### ISSUE THREAD

**Issue by DouglasHennrich** [hansemannn/titanium-google-maps#96]
`Google Maps SDK for iOS requires GoogleMaps.bundle to be part of your target under 'Copy Bundle Resources'`

`module v3.5.0`
`TiSDK 6.1.1.GA`
`Appc CLI 6.2.2`

**Comment by hansemannn** [comment]
Same for latest (3.6.1)? 3.5.0 was packaged by @yozef, hey @yozef, did you maybe packaged with `./build.py` instead of `appc ti build -p ios --build-only` ?

**Comment by DouglasHennrich** [comment]
With latest version(3.6.1) it works just fine =)

**Comment by m1ga** [comment]
@hansemannn had the same error when I've used `3.10.0` from the release page. I've cloned the repo and recompiled it locally (`appc ti build -p ios --build-only`) and it worked.

**Comment by joshualambert** [comment]
Hey y'all -- I'm seeing this bug again on TiShadow. Works fine with a normal iOS build. Any idea what might be happening here? `[ERROR] [iphone, 12.3.1, 192.168.84.103] Error: Google Maps SDK for iOS requires GoogleMaps.bundle to be part of your target under 'Copy Bundle Resources'`

**Comment by joshualambert** [comment]
The bug goes away if I don't use this module, so I think something's not quite meshing between TiShadow and Ti.GoogleMaps.

**Comment by hansemannn** [comment]
TiShadow is not able to handle bundle resources so far - not a module issue.

**Comment by joshualambert** [comment]
You'll find this interesting. I re-installed the Ti.GoogleMaps module entirely. Did a build without TiShadow. Then did another build with it -- it's working now. Idk why. But I'll roll with it! :D

**Comment by hansemannn** [comment]
Once compiled without TiShadow, it's copied so it will work. Lucky it's fine now.
