### ISSUE TITLE
Possible to add anno z-index?

### ISSUE THREAD

**Issue by mcongrove** [hansemannn/titanium-google-maps#97]
Is it possible to add a z-index property to an annotation?

Use case is that I add a custom annotation for the user's current location. After they do a search for nearby restaurants, I add their annotations to the map. If I'm zoomed out, the restaurant annotations display on top of my user location annotation.

**Comment by hansemannn** [comment]
Exposed as part of https://github.com/hansemannn/titanium-google-maps/commit/63d4f95cd7e6941060c1d33e916f8c05d35f0a17 and 2.7.0.

**Comment by mcongrove** [comment]
Hans... you're the man. Have I told you that lately? 👍
