### ISSUE TITLE
Add support for KML/GeoJSON

### ISSUE THREAD

**Issue by mcongrove** [hansemannn/titanium-google-maps#98]
Any mapping beyond simple points and lines requires support for shape file importing. Google Map iOS SDK supports import for KML and/or GeoJSON. Would be a great additional feature.

https://developers.google.com/maps/documentation/ios-sdk/utility/kml-geojson

**Comment by hansemannn** [comment]
You can pass a JSON-payload using the `mapStyle` property already, but the KML notation is something else. Marking as feature-proposal, but it's not planned, yet.

**Comment by hansemannn** [comment]
Had a few minutes at the airport, try it out: https://github.com/hansemannn/titanium-google-maps/pull/99

**Comment by mcongrove** [comment]
Works great. Any chance of adding a method to remove a KML/GeoJSON overlay?

**Comment by hansemannn** [comment]
There is, but with the way I hacked it yesterday it doesn't. I will work on making it an own proxy "Renderer" that then will have the methods `render`, `clear`.

**Comment by hansemannn** [comment]
Updated, closing this issue.
